version: '3'
networks:
    pokedle-net:
        ipam:
            config:
                - subnet: 172.19.0.0/24
volumes:
    app_volume:

services:
    db:
        build:
            context: .
            dockerfile: Dockerfile-db
        container_name: pokedle-db
        command: '--default-authentication-plugin=mysql_native_password'
        networks:
            - pokedle-net
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pokedle
        volumes:
            - '${PWD}/init_pokedle.sql:/docker-entrypoint-initdb.d/init_pokedle.sql'
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3306"]
            interval: 5s
            timeout: 10s
            retries: 5
    develop:
        build:
            context: .
            dockerfile: Dockerfile-develop
        container_name: develop
        volumes:
            - app_volume:/code
        command: tail -f /dev/null
    app1:
        build:
            context: .
            dockerfile: Dockerfile-app
        container_name: pokedle-app-1
        environment:
            - 'SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pokedle'
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root
        networks:
            - pokedle-net
        volumes:
            - app_volume:/opt/pokedle
        command: java -jar /opt/pokedle/pokedle.jar
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
    app2:
        build:
            context: .
            dockerfile: Dockerfile-app
        container_name: pokedle-app-2
        environment:
            - 'SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pokedle'
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root
        networks:
            - pokedle-net
        volumes:
            - app_volume:/opt/pokedle
        command: java -jar /opt/pokedle/pokedle.jar
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
    app3:
        build:
            context: .
            dockerfile: Dockerfile-app
        container_name: pokedle-app-3
        environment:
            - 'SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pokedle'
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root
        networks:
            - pokedle-net
        volumes:
            - app_volume:/opt/pokedle
        command: java -jar /opt/pokedle/pokedle.jar
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
    nginx:
        image: nginx
        container_name: pokedle-nginx
        ports:
            - '8080:80'
        networks:
            - pokedle-net
        depends_on:
            - app1
            - app2
            - app3
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf:ro'